import type { NextApiRequest, NextApiResponse } from "next";
import { featureAllowance, getPersistentAccess, limitReachedPayload, limitsAfterRun, recordUsageEvent } from "@/lib/workfusion/account-store";
import { getSession } from "@/lib/workfusion/session";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const access = await getPersistentAccess(getSession(req));
  const allowance = await featureAllowance(access, "download");
  if (!allowance.allowed) return res.status(402).json(limitReachedPayload(access, allowance));

  const content = String(req.body?.content || "// Generate or debug an EA before downloading.\n");
  const requested = String(req.body?.filename || "workfusion-ea.mq5");
  const filename = requested.endsWith(".mq4") || requested.endsWith(".mq5") ? requested : "workfusion-ea.mq5";
  await recordUsageEvent({ session: access.session, eventType: "feature_run", feature: "download", plan: access.plan });

  return res.status(200).json({
    file: `// Generated by Workfusion Trading AI\n${content}`,
    filename,
    feature: "download",
    plan: access.plan,
    remaining: limitsAfterRun(access, "download", allowance),
    storage: access.storage,
  });
}
