
/**
 * Challenge Configurations
 * Centralized configuration for all challenge tiers
 */

import { ChallengeConfiguration, ChallengeTier } from "./types";

export const challengeConfigurations: ChallengeConfiguration[] = [
  {
    id: "starter_10k",
    name: "Starter Challenge - $10K",
    tier: "STARTER",
    description: "Entry-level challenge for new traders. 10% profit target, 5% daily loss, 10% max drawdown.",
    accountSize: 10000,
    price: 99,
    resetPrice: 49,
    profitTargetPct: 10,
    maxDailyLossPct: 5,
    maxTotalLossPct: 10,
    minTradingDays: 3,
    maxPositionSizePct: 5,
    maxExposurePct: 20,
    maxLeverage: 30,
    allowedInstruments: ["FOREX", "INDICES", "COMMODITIES"],
    restrictedInstruments: [],
    newsRestrictionMinutes: 5,
    weekendHoldingAllowed: false,
    maxHoldingHours: 168,
    consistencyRule: { enabled: true, maxDailyProfitPctOfTotal: 30 },
    maxTradesPerDay: 20,
    minTradeDurationSeconds: 30,
    phaseCount: 1,
    scalingEnabled: true,
    profitSplitTraderPct: 80,
    profitSplitFirmPct: 20,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "standard_25k",
    name: "Standard Challenge - $25K",
    tier: "STANDARD",
    description: "Standard challenge for developing traders. 10% profit target, 5% daily loss, 10% max drawdown.",
    accountSize: 25000,
    price: 199,
    resetPrice: 99,
    profitTargetPct: 10,
    maxDailyLossPct: 5,
    maxTotalLossPct: 10,
    minTradingDays: 4,
    maxPositionSizePct: 5,
    maxExposurePct: 20,
    maxLeverage: 30,
    allowedInstruments: ["FOREX", "INDICES", "COMMODITIES"],
    restrictedInstruments: [],
    newsRestrictionMinutes: 5,
    weekendHoldingAllowed: false,
    maxHoldingHours: 168,
    consistencyRule: { enabled: true, maxDailyProfitPctOfTotal: 25 },
    maxTradesPerDay: 25,
    minTradeDurationSeconds: 30,
    phaseCount: 2,
    phaseConfigs: [
      { phase: 1, profitTargetPct: 10, maxDailyLossPct: 5, maxTotalLossPct: 10, minTradingDays: 3 },
      { phase: 2, profitTargetPct: 5, maxDailyLossPct: 5, maxTotalLossPct: 10, minTradingDays: 2 }
    ],
    scalingEnabled: true,
    profitSplitTraderPct: 80,
    profitSplitFirmPct: 20,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pro_50k",
    name: "Pro Challenge - $50K",
    tier: "PRO",
    description: "Professional challenge for experienced traders. 10% profit target, 4% daily loss, 8% max drawdown.",
    accountSize: 50000,
    price: 349,
    resetPrice: 149,
    profitTargetPct: 10,
    maxDailyLossPct: 4,
    maxTotalLossPct: 8,
    minTradingDays: 5,
    maxPositionSizePct: 4,
    maxExposurePct: 15,
    maxLeverage: 20,
    allowedInstruments: ["FOREX", "INDICES", "COMMODITIES"],
    restrictedInstruments: [],
    newsRestrictionMinutes: 10,
    weekendHoldingAllowed: false,
    maxHoldingHours: 168,
    consistencyRule: { enabled: true, maxDailyProfitPctOfTotal: 20 },
    maxTradesPerDay: 30,
    minTradeDurationSeconds: 60,
    phaseCount: 2,
    phaseConfigs: [
      { phase: 1, profitTargetPct: 10, maxDailyLossPct: 4, maxTotalLossPct: 8, minTradingDays: 4 },
      { phase: 2, profitTargetPct: 5, maxDailyLossPct: 4, maxTotalLossPct: 8, minTradingDays: 3 }
    ],
    scalingEnabled: true,
    profitSplitTraderPct: 85,
    profitSplitFirmPct: 15,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "advanced_100k",
    name: "Advanced Challenge - $100K",
    tier: "ADVANCED",
    description: "Advanced challenge for skilled traders. 8% profit target, 3% daily loss, 6% max drawdown.",
    accountSize: 100000,
    price: 599,
    resetPrice: 249,
    profitTargetPct: 8,
    maxDailyLossPct: 3,
    maxTotalLossPct: 6,
    minTradingDays: 7,
    maxPositionSizePct: 3,
    maxExposurePct: 10,
    maxLeverage: 15,
    allowedInstruments: ["FOREX", "INDICES", "COMMODITIES"],
    restrictedInstruments: [],
    newsRestrictionMinutes: 15,
    weekendHoldingAllowed: false,
    maxHoldingHours: 168,
    consistencyRule: { enabled: true, maxDailyProfitPctOfTotal: 15 },
    maxTradesPerDay: 20,
    minTradeDurationSeconds: 120,
    phaseCount: 2,
    phaseConfigs: [
      { phase: 1, profitTargetPct: 8, maxDailyLossPct: 3, maxTotalLossPct: 6, minTradingDays: 5 },
      { phase: 2, profitTargetPct: 4, maxDailyLossPct: 3, maxTotalLossPct: 6, minTradingDays: 4 }
    ],
    scalingEnabled: true,
    profitSplitTraderPct: 85,
    profitSplitFirmPct: 15,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "elite_200k",
    name: "Elite Challenge - $200K",
    tier: "ELITE",
    description: "Elite challenge for expert traders. 6% profit target, 2.5% daily loss, 5% max drawdown.",
    accountSize: 200000,
    price: 999,
    resetPrice: 399,
    profitTargetPct: 6,
    maxDailyLossPct: 2.5,
    maxTotalLossPct: 5,
    minTradingDays: 10,
    maxPositionSizePct: 2,
    maxExposurePct: 8,
    maxLeverage: 10,
    allowedInstruments: ["FOREX", "INDICES", "COMMODITIES"],
    restrictedInstruments: [],
    newsRestrictionMinutes: 30,
    weekendHoldingAllowed: false,
    maxHoldingHours: 168,
    consistencyRule: { enabled: true, maxDailyProfitPctOfTotal: 10 },
    maxTradesPerDay: 15,
    minTradeDurationSeconds: 300,
    phaseCount: 2,
    phaseConfigs: [
      { phase: 1, profitTargetPct: 6, maxDailyLossPct: 2.5, maxTotalLossPct: 5, minTradingDays: 7 },
      { phase: 2, profitTargetPct: 3, maxDailyLossPct: 2.5, maxTotalLossPct: 5, minTradingDays: 5 }
    ],
    scalingEnabled: true,
    profitSplitTraderPct: 90,
    profitSplitFirmPct: 10,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export function getChallengeConfig(challengeId: string): ChallengeConfiguration | undefined {
  return challengeConfigurations.find((c) => c.id === challengeId);
}

export function getActiveChallenges(): ChallengeConfiguration[] {
  return challengeConfigurations.filter((c) => c.isActive).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getChallengesByTier(tier: ChallengeTier): ChallengeConfiguration[] {
  return challengeConfigurations.filter((c) => c.tier === tier && c.isActive);
}

